thingsboard:
  host: "https://thingsboard.cloud"
  port: 8080
logger:
  format: "text"
  level: "info"
tb-override:
  files:
    css_filename: "custom.css"
    state_file: "active/state.json"
    nginx_config: "active/tb-override.conf"
    variables_filename: "variables.json"
  dirs:
    root_directory: "/opt/tb-override"
    active_directory: "active/assets"
    themes_directory: "themes"
  misc:
    skip_proxy_check: "true"
